### ISSUE TITLE
"On Push" is not a good approach. Please use "On release" 

### ISSUE THREAD

**Issue by jakariaemon** [anik-33/SE-Project-01-Source-Separation#1]
As i mentioned early, if we set the action for push, it will update the server on every push. But every push is not deployable. We should only deploy the release version such as 0.1.0, 0.2.0  

https://github.com/anik-33/SE-Project-01-Source-Separation/blob/46fc54ca046b13c888b583c0f2d2a70a36228eb4/.github/workflows/Sync_to_Hugging_Face_hub.yml#L3

**Comment by anik-33** [comment]
On push to on release updated.
